/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QualityPolicyRouteImport } from './routes/quality-policy'
import { Route as QmsPlugRouteImport } from './routes/qms-plug'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplaintsAppealsRouteImport } from './routes/complaints-appeals'
import { Route as CertificationPortalRouteImport } from './routes/certification-portal'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityPolicyRoute = QualityPolicyRouteImport.update({
  id: '/quality-policy',
  path: '/quality-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsPlugRoute = QmsPlugRouteImport.update({
  id: '/qms-plug',
  path: '/qms-plug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsAppealsRoute = ComplaintsAppealsRouteImport.update({
  id: '/complaints-appeals',
  path: '/complaints-appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationPortalRoute = CertificationPortalRouteImport.update({
  id: '/certification-portal',
  path: '/certification-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certification-portal': typeof CertificationPortalRoute
  '/complaints-appeals': typeof ComplaintsAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/history': typeof HistoryRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/qms-plug': typeof QmsPlugRoute
  '/quality-policy': typeof QualityPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certification-portal': typeof CertificationPortalRoute
  '/complaints-appeals': typeof ComplaintsAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/history': typeof HistoryRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/qms-plug': typeof QmsPlugRoute
  '/quality-policy': typeof QualityPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certification-portal': typeof CertificationPortalRoute
  '/complaints-appeals': typeof ComplaintsAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/history': typeof HistoryRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/qms-plug': typeof QmsPlugRoute
  '/quality-policy': typeof QualityPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/certification-portal'
    | '/complaints-appeals'
    | '/contact'
    | '/cookies'
    | '/history'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/qms-plug'
    | '/quality-policy'
    | '/resources'
    | '/services'
    | '/standards'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/certification-portal'
    | '/complaints-appeals'
    | '/contact'
    | '/cookies'
    | '/history'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/qms-plug'
    | '/quality-policy'
    | '/resources'
    | '/services'
    | '/standards'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/certification-portal'
    | '/complaints-appeals'
    | '/contact'
    | '/cookies'
    | '/history'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/qms-plug'
    | '/quality-policy'
    | '/resources'
    | '/services'
    | '/standards'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CertificationPortalRoute: typeof CertificationPortalRoute
  ComplaintsAppealsRoute: typeof ComplaintsAppealsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  HistoryRoute: typeof HistoryRoute
  IndustriesRoute: typeof IndustriesRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  QmsPlugRoute: typeof QmsPlugRoute
  QualityPolicyRoute: typeof QualityPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  StandardsRoute: typeof StandardsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-policy': {
      id: '/quality-policy'
      path: '/quality-policy'
      fullPath: '/quality-policy'
      preLoaderRoute: typeof QualityPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms-plug': {
      id: '/qms-plug'
      path: '/qms-plug'
      fullPath: '/qms-plug'
      preLoaderRoute: typeof QmsPlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints-appeals': {
      id: '/complaints-appeals'
      path: '/complaints-appeals'
      fullPath: '/complaints-appeals'
      preLoaderRoute: typeof ComplaintsAppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification-portal': {
      id: '/certification-portal'
      path: '/certification-portal'
      fullPath: '/certification-portal'
      preLoaderRoute: typeof CertificationPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CertificationPortalRoute: CertificationPortalRoute,
  ComplaintsAppealsRoute: ComplaintsAppealsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  HistoryRoute: HistoryRoute,
  IndustriesRoute: IndustriesRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  QmsPlugRoute: QmsPlugRoute,
  QualityPolicyRoute: QualityPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  StandardsRoute: StandardsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
