/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QualityPolicyRouteImport } from './routes/quality-policy'
import { Route as QmsSolutionsRouteImport } from './routes/qms-solutions'
import { Route as QmsPlugRouteImport } from './routes/qms-plug'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplaintsAppealsRouteImport } from './routes/complaints-appeals'
import { Route as CertificationPortalRouteImport } from './routes/certification-portal'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndustrySmeRouteImport } from './routes/industry/sme'
import { Route as IndustryOilGasRouteImport } from './routes/industry/oil-gas'
import { Route as IndustryMaritimeRouteImport } from './routes/industry/maritime'
import { Route as IndustryManufacturingRouteImport } from './routes/industry/manufacturing'
import { Route as IndustryLogisticsRouteImport } from './routes/industry/logistics'
import { Route as IndustryLaboratoriesRouteImport } from './routes/industry/laboratories'
import { Route as IndustryInspectionRouteImport } from './routes/industry/inspection'
import { Route as IndustryHealthcareRouteImport } from './routes/industry/healthcare'
import { Route as IndustryGovernmentRouteImport } from './routes/industry/government'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityPolicyRoute = QualityPolicyRouteImport.update({
  id: '/quality-policy',
  path: '/quality-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsSolutionsRoute = QmsSolutionsRouteImport.update({
  id: '/qms-solutions',
  path: '/qms-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsPlugRoute = QmsPlugRouteImport.update({
  id: '/qms-plug',
  path: '/qms-plug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsAppealsRoute = ComplaintsAppealsRouteImport.update({
  id: '/complaints-appeals',
  path: '/complaints-appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationPortalRoute = CertificationPortalRouteImport.update({
  id: '/certification-portal',
  path: '/certification-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySmeRoute = IndustrySmeRouteImport.update({
  id: '/industry/sme',
  path: '/industry/sme',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryOilGasRoute = IndustryOilGasRouteImport.update({
  id: '/industry/oil-gas',
  path: '/industry/oil-gas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryMaritimeRoute = IndustryMaritimeRouteImport.update({
  id: '/industry/maritime',
  path: '/industry/maritime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryManufacturingRoute = IndustryManufacturingRouteImport.update({
  id: '/industry/manufacturing',
  path: '/industry/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryLogisticsRoute = IndustryLogisticsRouteImport.update({
  id: '/industry/logistics',
  path: '/industry/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryLaboratoriesRoute = IndustryLaboratoriesRouteImport.update({
  id: '/industry/laboratories',
  path: '/industry/laboratories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryInspectionRoute = IndustryInspectionRouteImport.update({
  id: '/industry/inspection',
  path: '/industry/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryHealthcareRoute = IndustryHealthcareRouteImport.update({
  id: '/industry/healthcare',
  path: '/industry/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryGovernmentRoute = IndustryGovernmentRouteImport.update({
  id: '/industry/government',
  path: '/industry/government',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certification-portal': typeof CertificationPortalRoute
  '/complaints-appeals': typeof ComplaintsAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/history': typeof HistoryRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/qms-plug': typeof QmsPlugRoute
  '/qms-solutions': typeof QmsSolutionsRoute
  '/quality-policy': typeof QualityPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/industry/government': typeof IndustryGovernmentRoute
  '/industry/healthcare': typeof IndustryHealthcareRoute
  '/industry/inspection': typeof IndustryInspectionRoute
  '/industry/laboratories': typeof IndustryLaboratoriesRoute
  '/industry/logistics': typeof IndustryLogisticsRoute
  '/industry/manufacturing': typeof IndustryManufacturingRoute
  '/industry/maritime': typeof IndustryMaritimeRoute
  '/industry/oil-gas': typeof IndustryOilGasRoute
  '/industry/sme': typeof IndustrySmeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certification-portal': typeof CertificationPortalRoute
  '/complaints-appeals': typeof ComplaintsAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/history': typeof HistoryRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/qms-plug': typeof QmsPlugRoute
  '/qms-solutions': typeof QmsSolutionsRoute
  '/quality-policy': typeof QualityPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/industry/government': typeof IndustryGovernmentRoute
  '/industry/healthcare': typeof IndustryHealthcareRoute
  '/industry/inspection': typeof IndustryInspectionRoute
  '/industry/laboratories': typeof IndustryLaboratoriesRoute
  '/industry/logistics': typeof IndustryLogisticsRoute
  '/industry/manufacturing': typeof IndustryManufacturingRoute
  '/industry/maritime': typeof IndustryMaritimeRoute
  '/industry/oil-gas': typeof IndustryOilGasRoute
  '/industry/sme': typeof IndustrySmeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certification-portal': typeof CertificationPortalRoute
  '/complaints-appeals': typeof ComplaintsAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/history': typeof HistoryRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/qms-plug': typeof QmsPlugRoute
  '/qms-solutions': typeof QmsSolutionsRoute
  '/quality-policy': typeof QualityPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/industry/government': typeof IndustryGovernmentRoute
  '/industry/healthcare': typeof IndustryHealthcareRoute
  '/industry/inspection': typeof IndustryInspectionRoute
  '/industry/laboratories': typeof IndustryLaboratoriesRoute
  '/industry/logistics': typeof IndustryLogisticsRoute
  '/industry/manufacturing': typeof IndustryManufacturingRoute
  '/industry/maritime': typeof IndustryMaritimeRoute
  '/industry/oil-gas': typeof IndustryOilGasRoute
  '/industry/sme': typeof IndustrySmeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/certification-portal'
    | '/complaints-appeals'
    | '/contact'
    | '/cookies'
    | '/history'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/qms-plug'
    | '/qms-solutions'
    | '/quality-policy'
    | '/resources'
    | '/services'
    | '/standards'
    | '/terms'
    | '/industry/government'
    | '/industry/healthcare'
    | '/industry/inspection'
    | '/industry/laboratories'
    | '/industry/logistics'
    | '/industry/manufacturing'
    | '/industry/maritime'
    | '/industry/oil-gas'
    | '/industry/sme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/certification-portal'
    | '/complaints-appeals'
    | '/contact'
    | '/cookies'
    | '/history'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/qms-plug'
    | '/qms-solutions'
    | '/quality-policy'
    | '/resources'
    | '/services'
    | '/standards'
    | '/terms'
    | '/industry/government'
    | '/industry/healthcare'
    | '/industry/inspection'
    | '/industry/laboratories'
    | '/industry/logistics'
    | '/industry/manufacturing'
    | '/industry/maritime'
    | '/industry/oil-gas'
    | '/industry/sme'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/certification-portal'
    | '/complaints-appeals'
    | '/contact'
    | '/cookies'
    | '/history'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/qms-plug'
    | '/qms-solutions'
    | '/quality-policy'
    | '/resources'
    | '/services'
    | '/standards'
    | '/terms'
    | '/industry/government'
    | '/industry/healthcare'
    | '/industry/inspection'
    | '/industry/laboratories'
    | '/industry/logistics'
    | '/industry/manufacturing'
    | '/industry/maritime'
    | '/industry/oil-gas'
    | '/industry/sme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CertificationPortalRoute: typeof CertificationPortalRoute
  ComplaintsAppealsRoute: typeof ComplaintsAppealsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  HistoryRoute: typeof HistoryRoute
  IndustriesRoute: typeof IndustriesRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  QmsPlugRoute: typeof QmsPlugRoute
  QmsSolutionsRoute: typeof QmsSolutionsRoute
  QualityPolicyRoute: typeof QualityPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRoute
  StandardsRoute: typeof StandardsRoute
  TermsRoute: typeof TermsRoute
  IndustryGovernmentRoute: typeof IndustryGovernmentRoute
  IndustryHealthcareRoute: typeof IndustryHealthcareRoute
  IndustryInspectionRoute: typeof IndustryInspectionRoute
  IndustryLaboratoriesRoute: typeof IndustryLaboratoriesRoute
  IndustryLogisticsRoute: typeof IndustryLogisticsRoute
  IndustryManufacturingRoute: typeof IndustryManufacturingRoute
  IndustryMaritimeRoute: typeof IndustryMaritimeRoute
  IndustryOilGasRoute: typeof IndustryOilGasRoute
  IndustrySmeRoute: typeof IndustrySmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-policy': {
      id: '/quality-policy'
      path: '/quality-policy'
      fullPath: '/quality-policy'
      preLoaderRoute: typeof QualityPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms-solutions': {
      id: '/qms-solutions'
      path: '/qms-solutions'
      fullPath: '/qms-solutions'
      preLoaderRoute: typeof QmsSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms-plug': {
      id: '/qms-plug'
      path: '/qms-plug'
      fullPath: '/qms-plug'
      preLoaderRoute: typeof QmsPlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints-appeals': {
      id: '/complaints-appeals'
      path: '/complaints-appeals'
      fullPath: '/complaints-appeals'
      preLoaderRoute: typeof ComplaintsAppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification-portal': {
      id: '/certification-portal'
      path: '/certification-portal'
      fullPath: '/certification-portal'
      preLoaderRoute: typeof CertificationPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/sme': {
      id: '/industry/sme'
      path: '/industry/sme'
      fullPath: '/industry/sme'
      preLoaderRoute: typeof IndustrySmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/oil-gas': {
      id: '/industry/oil-gas'
      path: '/industry/oil-gas'
      fullPath: '/industry/oil-gas'
      preLoaderRoute: typeof IndustryOilGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/maritime': {
      id: '/industry/maritime'
      path: '/industry/maritime'
      fullPath: '/industry/maritime'
      preLoaderRoute: typeof IndustryMaritimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/manufacturing': {
      id: '/industry/manufacturing'
      path: '/industry/manufacturing'
      fullPath: '/industry/manufacturing'
      preLoaderRoute: typeof IndustryManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/logistics': {
      id: '/industry/logistics'
      path: '/industry/logistics'
      fullPath: '/industry/logistics'
      preLoaderRoute: typeof IndustryLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/laboratories': {
      id: '/industry/laboratories'
      path: '/industry/laboratories'
      fullPath: '/industry/laboratories'
      preLoaderRoute: typeof IndustryLaboratoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/inspection': {
      id: '/industry/inspection'
      path: '/industry/inspection'
      fullPath: '/industry/inspection'
      preLoaderRoute: typeof IndustryInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/healthcare': {
      id: '/industry/healthcare'
      path: '/industry/healthcare'
      fullPath: '/industry/healthcare'
      preLoaderRoute: typeof IndustryHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/government': {
      id: '/industry/government'
      path: '/industry/government'
      fullPath: '/industry/government'
      preLoaderRoute: typeof IndustryGovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CertificationPortalRoute: CertificationPortalRoute,
  ComplaintsAppealsRoute: ComplaintsAppealsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  HistoryRoute: HistoryRoute,
  IndustriesRoute: IndustriesRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  QmsPlugRoute: QmsPlugRoute,
  QmsSolutionsRoute: QmsSolutionsRoute,
  QualityPolicyRoute: QualityPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRoute,
  StandardsRoute: StandardsRoute,
  TermsRoute: TermsRoute,
  IndustryGovernmentRoute: IndustryGovernmentRoute,
  IndustryHealthcareRoute: IndustryHealthcareRoute,
  IndustryInspectionRoute: IndustryInspectionRoute,
  IndustryLaboratoriesRoute: IndustryLaboratoriesRoute,
  IndustryLogisticsRoute: IndustryLogisticsRoute,
  IndustryManufacturingRoute: IndustryManufacturingRoute,
  IndustryMaritimeRoute: IndustryMaritimeRoute,
  IndustryOilGasRoute: IndustryOilGasRoute,
  IndustrySmeRoute: IndustrySmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
