/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as QualityPolicyRouteImport } from './routes/quality-policy'
import { Route as QmsPlugRouteImport } from './routes/qms-plug'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as KnowledgeHubRouteImport } from './routes/knowledge-hub'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplaintsAppealsRouteImport } from './routes/complaints-appeals'
import { Route as CertificationPortalRouteImport } from './routes/certification-portal'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as KnowledgeHubIndexRouteImport } from './routes/knowledge-hub/index'
import { Route as ServicesVesselSurveysRouteImport } from './routes/services/vessel-surveys'
import { Route as ServicesTrainingConsultancyRouteImport } from './routes/services/training-consultancy'
import { Route as ServicesTechnicalReportingRouteImport } from './routes/services/technical-reporting'
import { Route as ServicesSampleLogisticsRouteImport } from './routes/services/sample-logistics'
import { Route as ServicesQualitySystemImplementationRouteImport } from './routes/services/quality-system-implementation'
import { Route as ServicesQualityAssuranceRouteImport } from './routes/services/quality-assurance'
import { Route as ServicesMarineInspectionRouteImport } from './routes/services/marine-inspection'
import { Route as ServicesDamageLossRouteImport } from './routes/services/damage-loss'
import { Route as ServicesConditionSurveysRouteImport } from './routes/services/condition-surveys'
import { Route as ServicesCertificationSupportRouteImport } from './routes/services/certification-support'
import { Route as ServicesCargoInspectionRouteImport } from './routes/services/cargo-inspection'
import { Route as ServicesAuditingRouteImport } from './routes/services/auditing'
import { Route as ServicesAccreditationSupportRouteImport } from './routes/services/accreditation-support'
import { Route as KnowledgeHubSlugRouteImport } from './routes/knowledge-hub/$slug'
import { Route as CertificationsIso17025RouteImport } from './routes/certifications/iso-17025'
import { Route as CertificationsIso17020RouteImport } from './routes/certifications/iso-17020'
import { Route as CertificationsIso15189RouteImport } from './routes/certifications/iso-15189'
import { Route as CertificationsFrameworkRouteImport } from './routes/certifications/$framework'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityPolicyRoute = QualityPolicyRouteImport.update({
  id: '/quality-policy',
  path: '/quality-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QmsPlugRoute = QmsPlugRouteImport.update({
  id: '/qms-plug',
  path: '/qms-plug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubRoute = KnowledgeHubRouteImport.update({
  id: '/knowledge-hub',
  path: '/knowledge-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsAppealsRoute = ComplaintsAppealsRouteImport.update({
  id: '/complaints-appeals',
  path: '/complaints-appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationPortalRoute = CertificationPortalRouteImport.update({
  id: '/certification-portal',
  path: '/certification-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const KnowledgeHubIndexRoute = KnowledgeHubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeHubRoute,
} as any)
const ServicesVesselSurveysRoute = ServicesVesselSurveysRouteImport.update({
  id: '/vessel-surveys',
  path: '/vessel-surveys',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTrainingConsultancyRoute =
  ServicesTrainingConsultancyRouteImport.update({
    id: '/training-consultancy',
    path: '/training-consultancy',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesTechnicalReportingRoute =
  ServicesTechnicalReportingRouteImport.update({
    id: '/technical-reporting',
    path: '/technical-reporting',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSampleLogisticsRoute = ServicesSampleLogisticsRouteImport.update({
  id: '/sample-logistics',
  path: '/sample-logistics',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesQualitySystemImplementationRoute =
  ServicesQualitySystemImplementationRouteImport.update({
    id: '/quality-system-implementation',
    path: '/quality-system-implementation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesQualityAssuranceRoute =
  ServicesQualityAssuranceRouteImport.update({
    id: '/quality-assurance',
    path: '/quality-assurance',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMarineInspectionRoute =
  ServicesMarineInspectionRouteImport.update({
    id: '/marine-inspection',
    path: '/marine-inspection',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDamageLossRoute = ServicesDamageLossRouteImport.update({
  id: '/damage-loss',
  path: '/damage-loss',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesConditionSurveysRoute =
  ServicesConditionSurveysRouteImport.update({
    id: '/condition-surveys',
    path: '/condition-surveys',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCertificationSupportRoute =
  ServicesCertificationSupportRouteImport.update({
    id: '/certification-support',
    path: '/certification-support',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCargoInspectionRoute = ServicesCargoInspectionRouteImport.update({
  id: '/cargo-inspection',
  path: '/cargo-inspection',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAuditingRoute = ServicesAuditingRouteImport.update({
  id: '/auditing',
  path: '/auditing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAccreditationSupportRoute =
  ServicesAccreditationSupportRouteImport.update({
    id: '/accreditation-support',
    path: '/accreditation-support',
    getParentRoute: () => ServicesRoute,
  } as any)
const KnowledgeHubSlugRoute = KnowledgeHubSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeHubRoute,
} as any)
const CertificationsIso17025Route = CertificationsIso17025RouteImport.update({
  id: '/certifications/iso-17025',
  path: '/certifications/iso-17025',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsIso17020Route = CertificationsIso17020RouteImport.update({
  id: '/certifications/iso-17020',
  path: '/certifications/iso-17020',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsIso15189Route = CertificationsIso15189RouteImport.update({
  id: '/certifications/iso-15189',
  path: '/certifications/iso-15189',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsFrameworkRoute = CertificationsFrameworkRouteImport.update({
  id: '/certifications/$framework',
  path: '/certifications/$framework',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certification-portal': typeof CertificationPortalRoute
  '/complaints-appeals': typeof ComplaintsAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/history': typeof HistoryRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-hub': typeof KnowledgeHubRouteWithChildren
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/qms-plug': typeof QmsPlugRoute
  '/quality-policy': typeof QualityPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/certifications/$framework': typeof CertificationsFrameworkRoute
  '/certifications/iso-15189': typeof CertificationsIso15189Route
  '/certifications/iso-17020': typeof CertificationsIso17020Route
  '/certifications/iso-17025': typeof CertificationsIso17025Route
  '/knowledge-hub/$slug': typeof KnowledgeHubSlugRoute
  '/services/accreditation-support': typeof ServicesAccreditationSupportRoute
  '/services/auditing': typeof ServicesAuditingRoute
  '/services/cargo-inspection': typeof ServicesCargoInspectionRoute
  '/services/certification-support': typeof ServicesCertificationSupportRoute
  '/services/condition-surveys': typeof ServicesConditionSurveysRoute
  '/services/damage-loss': typeof ServicesDamageLossRoute
  '/services/marine-inspection': typeof ServicesMarineInspectionRoute
  '/services/quality-assurance': typeof ServicesQualityAssuranceRoute
  '/services/quality-system-implementation': typeof ServicesQualitySystemImplementationRoute
  '/services/sample-logistics': typeof ServicesSampleLogisticsRoute
  '/services/technical-reporting': typeof ServicesTechnicalReportingRoute
  '/services/training-consultancy': typeof ServicesTrainingConsultancyRoute
  '/services/vessel-surveys': typeof ServicesVesselSurveysRoute
  '/knowledge-hub/': typeof KnowledgeHubIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certification-portal': typeof CertificationPortalRoute
  '/complaints-appeals': typeof ComplaintsAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/history': typeof HistoryRoute
  '/industries': typeof IndustriesRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/qms-plug': typeof QmsPlugRoute
  '/quality-policy': typeof QualityPolicyRoute
  '/resources': typeof ResourcesRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/certifications/$framework': typeof CertificationsFrameworkRoute
  '/certifications/iso-15189': typeof CertificationsIso15189Route
  '/certifications/iso-17020': typeof CertificationsIso17020Route
  '/certifications/iso-17025': typeof CertificationsIso17025Route
  '/knowledge-hub/$slug': typeof KnowledgeHubSlugRoute
  '/services/accreditation-support': typeof ServicesAccreditationSupportRoute
  '/services/auditing': typeof ServicesAuditingRoute
  '/services/cargo-inspection': typeof ServicesCargoInspectionRoute
  '/services/certification-support': typeof ServicesCertificationSupportRoute
  '/services/condition-surveys': typeof ServicesConditionSurveysRoute
  '/services/damage-loss': typeof ServicesDamageLossRoute
  '/services/marine-inspection': typeof ServicesMarineInspectionRoute
  '/services/quality-assurance': typeof ServicesQualityAssuranceRoute
  '/services/quality-system-implementation': typeof ServicesQualitySystemImplementationRoute
  '/services/sample-logistics': typeof ServicesSampleLogisticsRoute
  '/services/technical-reporting': typeof ServicesTechnicalReportingRoute
  '/services/training-consultancy': typeof ServicesTrainingConsultancyRoute
  '/services/vessel-surveys': typeof ServicesVesselSurveysRoute
  '/knowledge-hub': typeof KnowledgeHubIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/certification-portal': typeof CertificationPortalRoute
  '/complaints-appeals': typeof ComplaintsAppealsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/history': typeof HistoryRoute
  '/industries': typeof IndustriesRoute
  '/knowledge-hub': typeof KnowledgeHubRouteWithChildren
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/qms-plug': typeof QmsPlugRoute
  '/quality-policy': typeof QualityPolicyRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/certifications/$framework': typeof CertificationsFrameworkRoute
  '/certifications/iso-15189': typeof CertificationsIso15189Route
  '/certifications/iso-17020': typeof CertificationsIso17020Route
  '/certifications/iso-17025': typeof CertificationsIso17025Route
  '/knowledge-hub/$slug': typeof KnowledgeHubSlugRoute
  '/services/accreditation-support': typeof ServicesAccreditationSupportRoute
  '/services/auditing': typeof ServicesAuditingRoute
  '/services/cargo-inspection': typeof ServicesCargoInspectionRoute
  '/services/certification-support': typeof ServicesCertificationSupportRoute
  '/services/condition-surveys': typeof ServicesConditionSurveysRoute
  '/services/damage-loss': typeof ServicesDamageLossRoute
  '/services/marine-inspection': typeof ServicesMarineInspectionRoute
  '/services/quality-assurance': typeof ServicesQualityAssuranceRoute
  '/services/quality-system-implementation': typeof ServicesQualitySystemImplementationRoute
  '/services/sample-logistics': typeof ServicesSampleLogisticsRoute
  '/services/technical-reporting': typeof ServicesTechnicalReportingRoute
  '/services/training-consultancy': typeof ServicesTrainingConsultancyRoute
  '/services/vessel-surveys': typeof ServicesVesselSurveysRoute
  '/knowledge-hub/': typeof KnowledgeHubIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/certification-portal'
    | '/complaints-appeals'
    | '/contact'
    | '/cookies'
    | '/history'
    | '/industries'
    | '/knowledge-hub'
    | '/partners'
    | '/privacy'
    | '/qms-plug'
    | '/quality-policy'
    | '/resources'
    | '/services'
    | '/standards'
    | '/terms'
    | '/certifications/$framework'
    | '/certifications/iso-15189'
    | '/certifications/iso-17020'
    | '/certifications/iso-17025'
    | '/knowledge-hub/$slug'
    | '/services/accreditation-support'
    | '/services/auditing'
    | '/services/cargo-inspection'
    | '/services/certification-support'
    | '/services/condition-surveys'
    | '/services/damage-loss'
    | '/services/marine-inspection'
    | '/services/quality-assurance'
    | '/services/quality-system-implementation'
    | '/services/sample-logistics'
    | '/services/technical-reporting'
    | '/services/training-consultancy'
    | '/services/vessel-surveys'
    | '/knowledge-hub/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/certification-portal'
    | '/complaints-appeals'
    | '/contact'
    | '/cookies'
    | '/history'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/qms-plug'
    | '/quality-policy'
    | '/resources'
    | '/standards'
    | '/terms'
    | '/certifications/$framework'
    | '/certifications/iso-15189'
    | '/certifications/iso-17020'
    | '/certifications/iso-17025'
    | '/knowledge-hub/$slug'
    | '/services/accreditation-support'
    | '/services/auditing'
    | '/services/cargo-inspection'
    | '/services/certification-support'
    | '/services/condition-surveys'
    | '/services/damage-loss'
    | '/services/marine-inspection'
    | '/services/quality-assurance'
    | '/services/quality-system-implementation'
    | '/services/sample-logistics'
    | '/services/technical-reporting'
    | '/services/training-consultancy'
    | '/services/vessel-surveys'
    | '/knowledge-hub'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/certification-portal'
    | '/complaints-appeals'
    | '/contact'
    | '/cookies'
    | '/history'
    | '/industries'
    | '/knowledge-hub'
    | '/partners'
    | '/privacy'
    | '/qms-plug'
    | '/quality-policy'
    | '/resources'
    | '/services'
    | '/standards'
    | '/terms'
    | '/certifications/$framework'
    | '/certifications/iso-15189'
    | '/certifications/iso-17020'
    | '/certifications/iso-17025'
    | '/knowledge-hub/$slug'
    | '/services/accreditation-support'
    | '/services/auditing'
    | '/services/cargo-inspection'
    | '/services/certification-support'
    | '/services/condition-surveys'
    | '/services/damage-loss'
    | '/services/marine-inspection'
    | '/services/quality-assurance'
    | '/services/quality-system-implementation'
    | '/services/sample-logistics'
    | '/services/technical-reporting'
    | '/services/training-consultancy'
    | '/services/vessel-surveys'
    | '/knowledge-hub/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CertificationPortalRoute: typeof CertificationPortalRoute
  ComplaintsAppealsRoute: typeof ComplaintsAppealsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  HistoryRoute: typeof HistoryRoute
  IndustriesRoute: typeof IndustriesRoute
  KnowledgeHubRoute: typeof KnowledgeHubRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  QmsPlugRoute: typeof QmsPlugRoute
  QualityPolicyRoute: typeof QualityPolicyRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  StandardsRoute: typeof StandardsRoute
  TermsRoute: typeof TermsRoute
  CertificationsFrameworkRoute: typeof CertificationsFrameworkRoute
  CertificationsIso15189Route: typeof CertificationsIso15189Route
  CertificationsIso17020Route: typeof CertificationsIso17020Route
  CertificationsIso17025Route: typeof CertificationsIso17025Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-policy': {
      id: '/quality-policy'
      path: '/quality-policy'
      fullPath: '/quality-policy'
      preLoaderRoute: typeof QualityPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qms-plug': {
      id: '/qms-plug'
      path: '/qms-plug'
      fullPath: '/qms-plug'
      preLoaderRoute: typeof QmsPlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub': {
      id: '/knowledge-hub'
      path: '/knowledge-hub'
      fullPath: '/knowledge-hub'
      preLoaderRoute: typeof KnowledgeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints-appeals': {
      id: '/complaints-appeals'
      path: '/complaints-appeals'
      fullPath: '/complaints-appeals'
      preLoaderRoute: typeof ComplaintsAppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification-portal': {
      id: '/certification-portal'
      path: '/certification-portal'
      fullPath: '/certification-portal'
      preLoaderRoute: typeof CertificationPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/knowledge-hub/': {
      id: '/knowledge-hub/'
      path: '/'
      fullPath: '/knowledge-hub/'
      preLoaderRoute: typeof KnowledgeHubIndexRouteImport
      parentRoute: typeof KnowledgeHubRoute
    }
    '/services/vessel-surveys': {
      id: '/services/vessel-surveys'
      path: '/vessel-surveys'
      fullPath: '/services/vessel-surveys'
      preLoaderRoute: typeof ServicesVesselSurveysRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/training-consultancy': {
      id: '/services/training-consultancy'
      path: '/training-consultancy'
      fullPath: '/services/training-consultancy'
      preLoaderRoute: typeof ServicesTrainingConsultancyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/technical-reporting': {
      id: '/services/technical-reporting'
      path: '/technical-reporting'
      fullPath: '/services/technical-reporting'
      preLoaderRoute: typeof ServicesTechnicalReportingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/sample-logistics': {
      id: '/services/sample-logistics'
      path: '/sample-logistics'
      fullPath: '/services/sample-logistics'
      preLoaderRoute: typeof ServicesSampleLogisticsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/quality-system-implementation': {
      id: '/services/quality-system-implementation'
      path: '/quality-system-implementation'
      fullPath: '/services/quality-system-implementation'
      preLoaderRoute: typeof ServicesQualitySystemImplementationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/quality-assurance': {
      id: '/services/quality-assurance'
      path: '/quality-assurance'
      fullPath: '/services/quality-assurance'
      preLoaderRoute: typeof ServicesQualityAssuranceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/marine-inspection': {
      id: '/services/marine-inspection'
      path: '/marine-inspection'
      fullPath: '/services/marine-inspection'
      preLoaderRoute: typeof ServicesMarineInspectionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/damage-loss': {
      id: '/services/damage-loss'
      path: '/damage-loss'
      fullPath: '/services/damage-loss'
      preLoaderRoute: typeof ServicesDamageLossRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/condition-surveys': {
      id: '/services/condition-surveys'
      path: '/condition-surveys'
      fullPath: '/services/condition-surveys'
      preLoaderRoute: typeof ServicesConditionSurveysRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/certification-support': {
      id: '/services/certification-support'
      path: '/certification-support'
      fullPath: '/services/certification-support'
      preLoaderRoute: typeof ServicesCertificationSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cargo-inspection': {
      id: '/services/cargo-inspection'
      path: '/cargo-inspection'
      fullPath: '/services/cargo-inspection'
      preLoaderRoute: typeof ServicesCargoInspectionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/auditing': {
      id: '/services/auditing'
      path: '/auditing'
      fullPath: '/services/auditing'
      preLoaderRoute: typeof ServicesAuditingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/accreditation-support': {
      id: '/services/accreditation-support'
      path: '/accreditation-support'
      fullPath: '/services/accreditation-support'
      preLoaderRoute: typeof ServicesAccreditationSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/knowledge-hub/$slug': {
      id: '/knowledge-hub/$slug'
      path: '/$slug'
      fullPath: '/knowledge-hub/$slug'
      preLoaderRoute: typeof KnowledgeHubSlugRouteImport
      parentRoute: typeof KnowledgeHubRoute
    }
    '/certifications/iso-17025': {
      id: '/certifications/iso-17025'
      path: '/certifications/iso-17025'
      fullPath: '/certifications/iso-17025'
      preLoaderRoute: typeof CertificationsIso17025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/iso-17020': {
      id: '/certifications/iso-17020'
      path: '/certifications/iso-17020'
      fullPath: '/certifications/iso-17020'
      preLoaderRoute: typeof CertificationsIso17020RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/iso-15189': {
      id: '/certifications/iso-15189'
      path: '/certifications/iso-15189'
      fullPath: '/certifications/iso-15189'
      preLoaderRoute: typeof CertificationsIso15189RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/$framework': {
      id: '/certifications/$framework'
      path: '/certifications/$framework'
      fullPath: '/certifications/$framework'
      preLoaderRoute: typeof CertificationsFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KnowledgeHubRouteChildren {
  KnowledgeHubSlugRoute: typeof KnowledgeHubSlugRoute
  KnowledgeHubIndexRoute: typeof KnowledgeHubIndexRoute
}

const KnowledgeHubRouteChildren: KnowledgeHubRouteChildren = {
  KnowledgeHubSlugRoute: KnowledgeHubSlugRoute,
  KnowledgeHubIndexRoute: KnowledgeHubIndexRoute,
}

const KnowledgeHubRouteWithChildren = KnowledgeHubRoute._addFileChildren(
  KnowledgeHubRouteChildren,
)

interface ServicesRouteChildren {
  ServicesAccreditationSupportRoute: typeof ServicesAccreditationSupportRoute
  ServicesAuditingRoute: typeof ServicesAuditingRoute
  ServicesCargoInspectionRoute: typeof ServicesCargoInspectionRoute
  ServicesCertificationSupportRoute: typeof ServicesCertificationSupportRoute
  ServicesConditionSurveysRoute: typeof ServicesConditionSurveysRoute
  ServicesDamageLossRoute: typeof ServicesDamageLossRoute
  ServicesMarineInspectionRoute: typeof ServicesMarineInspectionRoute
  ServicesQualityAssuranceRoute: typeof ServicesQualityAssuranceRoute
  ServicesQualitySystemImplementationRoute: typeof ServicesQualitySystemImplementationRoute
  ServicesSampleLogisticsRoute: typeof ServicesSampleLogisticsRoute
  ServicesTechnicalReportingRoute: typeof ServicesTechnicalReportingRoute
  ServicesTrainingConsultancyRoute: typeof ServicesTrainingConsultancyRoute
  ServicesVesselSurveysRoute: typeof ServicesVesselSurveysRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAccreditationSupportRoute: ServicesAccreditationSupportRoute,
  ServicesAuditingRoute: ServicesAuditingRoute,
  ServicesCargoInspectionRoute: ServicesCargoInspectionRoute,
  ServicesCertificationSupportRoute: ServicesCertificationSupportRoute,
  ServicesConditionSurveysRoute: ServicesConditionSurveysRoute,
  ServicesDamageLossRoute: ServicesDamageLossRoute,
  ServicesMarineInspectionRoute: ServicesMarineInspectionRoute,
  ServicesQualityAssuranceRoute: ServicesQualityAssuranceRoute,
  ServicesQualitySystemImplementationRoute:
    ServicesQualitySystemImplementationRoute,
  ServicesSampleLogisticsRoute: ServicesSampleLogisticsRoute,
  ServicesTechnicalReportingRoute: ServicesTechnicalReportingRoute,
  ServicesTrainingConsultancyRoute: ServicesTrainingConsultancyRoute,
  ServicesVesselSurveysRoute: ServicesVesselSurveysRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CertificationPortalRoute: CertificationPortalRoute,
  ComplaintsAppealsRoute: ComplaintsAppealsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  HistoryRoute: HistoryRoute,
  IndustriesRoute: IndustriesRoute,
  KnowledgeHubRoute: KnowledgeHubRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  QmsPlugRoute: QmsPlugRoute,
  QualityPolicyRoute: QualityPolicyRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRouteWithChildren,
  StandardsRoute: StandardsRoute,
  TermsRoute: TermsRoute,
  CertificationsFrameworkRoute: CertificationsFrameworkRoute,
  CertificationsIso15189Route: CertificationsIso15189Route,
  CertificationsIso17020Route: CertificationsIso17020Route,
  CertificationsIso17025Route: CertificationsIso17025Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
